name: onus
description: "A new Flutter project."
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  http: ^1.3.0
  image_picker: ^1.1.2
  crypto: ^3.0.6
  path_provider: ^2.1.5
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  video_player: ^2.9.5
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/electrical.jpg
    - assets/plumbing.jpg
    - assets/carpentry.jpg
    - assets/masonry.jpg
    - assets/promotion.jpg
    - assets/materials.jpeg
    - assets/land.jpg
    - assets/land2.jpg
    - assets/building-consultant.jpeg
    - assets/consulting.jpg
    - assets/concrete_pouring.png
    - assets/house_painting.jpg
    - assets/electric_wiring.jpg
    - assets/equipment_rental.png